### ISSUE TITLE
How to convert rgb and depth to raw?

### ISSUE THREAD

**Issue by kuwan2e** [smartroboticslab/mid-fusion#1]
Hi there.
Thank you and your team for all the hard work.
I see you compress rgb and depth data into a file in raw format.
I want to know is there any script or code to simply convert my rgb and depth data to raw file?
Best regards.

**Comment by binbin-xu** [comment]
Hi,

Thank you very much for your interest in our work. The method for converting your data to the raw format depends on how you collected it. If you collected your data in the TUM or IC-NUIM format, you can use our program, [scene2raw](https://github.com/smartroboticslab/mid-fusion/blob/main/apps/kfusion/thirdparty/scene2raw.cpp), which is included in mid-fusion.

Alternatively, if you recorded your data from an Asus Kinect using a program such as [logger2](https://github.com/mp3guy/Logger2), you can use our code, [vs2raw](https://github.com/binbin-xu/vs2raw), to convert from klg files (which are used in elasticfusion and maskfusion) to the raw format.

If you recorded your data using a realsense camera, you can use my [rs-logger](https://github.com/binbin-xu/rs-logger) to directly record your live raw data.

In practice, I have tried all three approaches. 

We hope this information helps you solve your problem.

Best,
Binbin
